# Generated by Django 6.0.4 on 2026-05-11 07:33

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_email', models.EmailField(max_length=254, unique=True)),
                ('user_name', models.CharField(blank=True, max_length=100, null=True)),
                ('user_phone', models.CharField(blank=True, max_length=100, null=True)),
                ('password', models.TextField()),
                ('verified_status', models.BooleanField(default=False)),
                ('account_registration', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user_table',
            },
        ),
        migrations.CreateModel(
            name='Appkey',
            fields=[
                ('appkeyID', models.AutoField(primary_key=True, serialize=False)),
                ('appkey', models.TextField()),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('revoked_status', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontEnd.user')),
            ],
            options={
                'db_table': 'appkey_table',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('session_id', models.AutoField(primary_key=True, serialize=False)),
                ('last_active', models.DateTimeField(auto_now=True)),
                ('session_expiry', models.DateTimeField()),
                ('ip_address', models.GenericIPAddressField()),
                ('access_revoked', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontEnd.user')),
            ],
            options={
                'db_table': 'session_table',
                'indexes': [models.Index(fields=['user'], name='session_tab_user_id_61d27a_idx'), models.Index(fields=['session_expiry'], name='session_tab_session_98bb57_idx')],
            },
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('otp_id', models.AutoField(primary_key=True, serialize=False)),
                ('otp_code', models.CharField(max_length=6)),
                ('otp_expiry', models.DateTimeField(default=datetime.datetime(2026, 5, 11, 15, 38, 58, 226848))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontEnd.user')),
            ],
            options={
                'db_table': 'otp_table',
                'indexes': [models.Index(fields=['user'], name='otp_table_user_id_b4212a_idx'), models.Index(fields=['otp_code'], name='otp_table_otp_cod_a85798_idx')],
            },
        ),
    ]
