# Generated by Django 6.0.4 on 2026-05-20 08:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontEnd', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='otp_expiry',
        ),
        migrations.AddField(
            model_name='otp',
            name='code_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='otp',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 20, 8, 45, 55)),
        ),
        migrations.AlterField(
            model_name='otp',
            name='otp_code',
            field=models.TextField(),
        ),
    ]
