# Generated by Django 6.0.4 on 2026-05-20 08:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontEnd', '0002_remove_otp_otp_expiry_otp_code_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 20, 8, 50, 52, 158903, tzinfo=datetime.timezone.utc)),
        ),
    ]
