# Generated by Django 6.0.4 on 2026-05-20 08:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontEnd', '0003_alter_otp_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
